name: Build and Deploy Fast

on: [push, pull_request]

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi
        run: echo "chicks"
      - name: install python
        uses: actions/setup-python@v3
        with: 
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: install and run pytest
        run: |
          pip install pytest
          pytest



# on:
#   push:
#     branches:
#       - 'main'
#   pull_request:
#     branches:
#       - 'test_branch'